# Generated by Django 3.1.4 on 2021-01-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210109_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Makaleye Resim Ekleyin',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Resim Ekleyin'),
        ),
    ]
